# Generated by Django 6.0.4 on 2026-05-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_sport_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='team1_logo',
            field=models.ImageField(blank=True, null=True, upload_to='events/teams/'),
        ),
        migrations.AddField(
            model_name='event',
            name='team1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='team2_logo',
            field=models.ImageField(blank=True, null=True, upload_to='events/teams/'),
        ),
        migrations.AddField(
            model_name='event',
            name='team2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
