# Generated by Django 5.0.6 on 2026-05-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_manualticketrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualticketrequest',
            name='target_full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='manualticketrequest',
            name='target_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
