# Generated by Django 5.0.6 on 2026-06-20 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_ticketscan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_paid_ticket_per_user_event',
        ),
        migrations.AddField(
            model_name='manualticketrequest',
            name='seat_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualticketrequest',
            name='section',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='section',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('is_paid', True)), fields=('event', 'seat_type', 'section', 'seat_number'), name='unique_paid_seat_per_event'),
        ),
    ]
